import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
	docsSidebar: [
		'index',
		{
			type: 'category',
			label: 'Getting Started',
			link: { type: 'doc', id: 'getting-started/index' },
			items: [{ type: 'autogenerated', dirName: 'getting-started' }]
		},
		{
			type: 'category',
			label: 'Guides',
			link: { type: 'doc', id: 'guides/index' },
			items: [{ type: 'autogenerated', dirName: 'guides' }]
		},
		{
			type: 'category',
			label: 'Reference',
			link: { type: 'doc', id: 'reference/index' },
			items: [{ type: 'autogenerated', dirName: 'reference' }]
		},
		{
			type: 'category',
			label: 'Explanation',
			link: { type: 'doc', id: 'explanation/index' },
			items: [{ type: 'autogenerated', dirName: 'explanation' }]
		},
		{
			type: 'category',
			label: 'Support',
			link: { type: 'doc', id: 'support/index' },
			items: [{ type: 'autogenerated', dirName: 'support' }]
		}
	]
};

export default sidebars;
