import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
	docsSidebar: [
		'index',
		{
			type: 'category',
			label: 'Getting Started',
			items: [{ type: 'autogenerated', dirName: 'getting-started' }]
		},
		{
			type: 'category',
			label: 'Guides',
			items: [{ type: 'autogenerated', dirName: 'guides' }]
		},
		{
			type: 'category',
			label: 'Reference',
			items: [{ type: 'autogenerated', dirName: 'reference' }]
		},
		{
			type: 'category',
			label: 'Explanation',
			items: [{ type: 'autogenerated', dirName: 'explanation' }]
		},
		{
			type: 'category',
			label: 'Support',
			items: [{ type: 'autogenerated', dirName: 'support' }]
		}
	]
};

export default sidebars;
